version: '3.1'

services:

  db:
    image: mysql:5.5
    container_name: MysqlInstance
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: angular
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - 3306:3306  